[package]
name = "rjvm"
version = "0.1.0"
authors = ["Sam <sam@gpsm.co.uk>"]

[dependencies]
glob = "0.2.11"
byteorder = "1.0.0"
rand = "0.3"
assert_approx_eq = "1.0.0"
checksum = "0.2.1"
zip = "0.2.6"